spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: api
    password: api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaWJyYXJ5LXNlcnZpY2UiLCJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTUxMzkyMDAsImV4cCI6MTY5NTE0MjgwMCwiYXVkIjoibGlicmFyeS1zZXJ2aWNlIn0.XcMx0SXBv6Kw8r1wqeJZpPVHgITovPv7mlymg6F-1mc"
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/