spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:
        - id: book-service-route
          uri: lb://book-service/
          predicates:
            - Path=/book-service/
          filters:
            - StripPrefix=1
        - id: library-service-route
          uri: lb://library-service/
          predicates:
            - Path=/library-service/
          filters:
            - StripPrefix=1
        - id: authentication-service-route
          uri: lb://authentication-service/
          predicates:
            - Path=/authentication-service/
          filters:
            - StripPrefix=1
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.http.server.reactive: DEBUG
      org.springframework.web.reactive: DEBUG
      reactor.ipc.netty: DEBUG
      reactor.netty: DEBUG
server:
  port: 8080
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /book-service/v3/api-docs
      - name: library-service
        url: /library-service/v3/api-docs
      - name: authentication-service
        url: /authentication-service/v3/api-docs
api-docs:
  path: /v3/api-docs
swagger-ui:
  path: /swagger-ui.html