\c users;

CREATE TABLE public.user_credentials (
                                       id bigint NOT NULL,
                                       username character varying(100) NOT NULL,
                                       password character varying(100) NOT NULL
);

ALTER TABLE public.user_credentials OWNER TO api;

ALTER TABLE public.user_credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_credentials
    ADD CONSTRAINT user_credentials_pkey PRIMARY KEY (id);
