spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: api
    password: api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html